### ISSUE TITLE
тотально неверная логика ;-)

### ISSUE THREAD

**Issue by admzzz** [uzen/dnscrypt-android#1]
0) никогда не стоит давать рутовым приложениям выход в инет.
1) 5353ий ни на фиг: грамотнее  использовать 53ий, открыть его для юзера dnscrypt под рутом и форкнуть запущенный из-под рута (из инит.ди) процесс для того же юзера, проверить, что всё фурычит (тестовый диэнэс-запрос) и убить рутового родителя.
2) эйэфволл часто глючит с правилами (а иногда глючит просто после долгой непрерывной работы) и пишет их не проверяя уникальность, посему при старте, применении_правил и выключении эйэфволла осмысленно грохать/чистить ФСЁ (чтоб заведомо защитить инет от себя, если нету эйэфволла), а при старте и применении_правил перевоссоздавать желаемое из своего (отдельного) скрипта.
3) вешать диэнэскрипт осмысленно не только на 53ий, но и на 443ий - чтоб пропустили в бесплатных_вайфаях/корпоративах, и дефолтовый список серверов, соответственно, должен включать пару работающих по DoH диэнэскриптовских-серверов (сервера - из актуального списка, причём только шифрующие и обязательно НЕ логирующие (т.е. яндекс сразу в жопу)).
4) /system/xbin/dnscrypt-proxy - неудобно, придётся каждый раз звать по полному имени, правильнее положить в /system/bin.

**Comment by uzen** [comment]
открыть его для юзера dnscrypt под рутом и форкнуть запущенный из-под рута (из инит.ди) процесс для того же юзера, проверить, что всё фурычит (тестовый диэнэс-запрос) и убить рутового родителя.

Можете привести пример того, как будет выглядеть код.

**Comment by admzzz** [comment]
гугл в помощь + http://blog.n01se.net/blog-n01se-net-p-145.html + тема скриптов на 4пда

**Comment by admzzz** [comment]
страусиное закрытие ишью. ;-Ъ

вот рабочий пример /etc/init.d/01net - его надо расширить, чтоб блокировался не только вайфай, но и мобильные данные.

`#!/system/bin/sh

#v4.2
mlog=/data/local/net.log;
if [ -a $mlog ]; then
rm $mlog;
fi;

f=/data/local/ipx.txt
if [ -a $f ]; then
rm $f;
fi;

echo "\nNet" | tee -a $mlog;

WIFI=wlan0;
# имя интерфейса wifi
IPT=/system/bin/iptables;
IP6T=/system/bin/ip6tables;

echo "ipv6\n" | tee -a $mlog;
# Блокировка протокола ip v6.
$IP6T -P INPUT DROP
$IP6T -P OUTPUT DROP
$IP6T -P FORWARD DROP
$IP6T -F mreject
$IP6T -N mreject
$IP6T -A mreject -j DROP
$IP6T -L INPUT | grep -q 'mreject' || $IP6T -I INPUT 1 -j "mreject"
$IP6T -L OUTPUT | grep -q 'mreject' || $IP6T -I OUTPUT 1 -j "mreject"
$IP6T -L FORWARD | grep -q 'mreject' || $IP6T -I FORWARD 1 -j "mreject"
echo "1" > /proc/sys/net/ipv6/conf/all/disable_ipv6
echo "1" > /proc/sys/net/ipv6/conf/default/disable_ipv6
if [-d /proc /sys/net/ipv6/conf/$WIFI]; then
echo "1" > /proc/sys/net/ipv6/conf/$WIFI/disable_ipv6;
fi;

echo "ipv4\n" | tee -a $mlog;
# Блокировка пакетов протокола IP v4.
$IPT -P INPUT DROP
$IPT -P OUTPUT DROP
$IPT -P FORWARD DROP
$IPT -F mreject
$IPT -N mreject
$IPT -A mreject -j DROP
$IPT -L INPUT | grep -q 'mreject' || $IPT -I INPUT 1 -j "mreject"
$IPT -L OUTPUT | grep -q 'mreject' || $IPT -I OUTPUT 1 -j "mreject"
$IPT -L FORWARD | grep -q 'mreject' || $IPT -I FORWARD 1 -j "mreject"
echo "1" > /proc/sys/net/ipv4/conf/all/disable_policy
echo "1" > /proc/sys/net/ipv4/conf/default/disable_policy
if [-d /proc /sys/net/ipv4/conf/$WIFI]; then
echo "1" > /proc/sys/net/ipv4/conf/$WIFI/disable_policy;
fi;
echo "happy end" | tee -a $mlog;
echo >> $mlog`
