### ISSUE TITLE
command to edit proxy.toml

### ISSUE THREAD

**Issue by bozchan** [uzen/dnscrypt-android#2]
if i want to use 1 resolver only (e.g cloudfare), is there any method for common people like me?

was trying edit dnscrypt_proxy.toml but it is said read only (protected)
was using ES explorer changed permission, edited dnscrypt_proxy.toml then saved, but dnsproxy services failed to start (not running).

Thanks in advance

**Comment by uzen** [comment]
it should look like this
server_names = ['cloudflare'] 
or so if you use ipv6
server_names = ['cloudflare', 'cloudflare-ipv6']
check syntax for extra errors or commas
also your explorer could change the rights to access files (755) or the owner(root). 
```
$ ls -la /etc/dnscrypt-proxy/
total 80
drwxr-xr-x  2 root root  4096 2018-10-07 17:24 .
drwxr-xr-x 17 root root  4096 2018-10-01 13:49 ..
-rwxr-xr-x  1 root root   841 2008-08-01 18:00 blacklist
-rwxr-xr-x  1 root root   714 2008-08-01 18:00 cloaking-rules
-rwxr-xr-x  1 root root 14747 2008-08-01 18:00 dnscrypt-proxy.toml
-rwxr-xr-x  1 root root   600 2008-08-01 18:00 forwarding-rules
-rwxr-xr-x  1 root root  2192 2018-10-16 22:24 init-functions
-rwxr-xr-x  1 root root  1762 2008-08-01 18:00 iptables-rules
-rwxr-xr-x  1 root root 27876 2008-08-01 18:00 public-resolvers.md
-rwxr-xr-x  1 root root   307 2008-08-01 18:00 public-resolvers.md.minisig
-rwxr-xr-x  1 root root   723 2008-08-01 18:00 whitelist
```

**Comment by uzen** [comment]
UPD: check what dnscrypt doesn't like in your configuration. running it in a terminal with root rights (example in termux)

**Comment by bozchan** [comment]
Thanks for the reply,

here is the things, the original package and config is running well, UDP check ($ls -la) in terminal exactly same as u wrote above.

the problem is original configuration dnscrypt-proxy.toml consist of server_names = ['scaleway-fr','google','cloudflare'] (this config tested in dnsleaktest.com resulted only 2 resolver, scaleway and cloudflare, google resolver not appear in the dnsleaktest.com)

when i want to change to server_names = ['cloudflare'] i can not save it
here what i do ;
1. open dnscrypt-proxy.toml using SD Maid Pro (root access using magisk)
2. change .toml permission  from rwxr-xr-x to rwxrwxrwx
3. open it with Quickedit
4. change server_names = ['cloudflare']
5. save (pop up warning "Error when saving file" java.io.FileNotFoundException: open failed: EROFS (read only file system)

**Comment by bozchan** [comment]
woops, i did make it
copy dnscrypt-proxy.toml to sdcard, then edit server_name = ['cloudflare']
then replace original within system/etc/dnscrypt-proxy/  with above edited then restart services, done!
detected resolver on dnsleaktest.com now is cloudflare only.

but when i tried changing server_name = ['google'] and require_nolog = false
still no luck, the result no connection, probably because the system has no resolver

well, i will stay with cloudflare only  at the moment. thanks a lot
